[build]
  command = "npm rebuild sweph && npm run build"
  functions = "dist/functions"
  
[build.environment]
  PYTHON = "/usr/bin/python3"
  CC = "gcc"
  CXX = "g++"

[dev]
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/astro-api/:splat"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

  # Flags "sweph" as an external node module for all functions
  external_node_modules = ["sweph"]
