# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := sweph
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=sweph' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_LARGEFILE_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-DNAPI_DISABLE_CPP_EXCEPTIONS' \
	'-DBUILDING_NODE_EXTENSION' \
	'-DDEBUG' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-exceptions \
	-fno-strict-aliasing \
	-std=gnu++17

INCS_Debug := \
	-I/root/.cache/node-gyp/22.19.0/include/node \
	-I/root/.cache/node-gyp/22.19.0/src \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/config \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/22.19.0/deps/uv/include \
	-I/root/.cache/node-gyp/22.19.0/deps/zlib \
	-I/root/.cache/node-gyp/22.19.0/deps/v8/include \
	-I$(srcdir)/../node-addon-api \
	-I$(srcdir)/src \
	-I$(srcdir)/swisseph

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=sweph' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_LARGEFILE_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-DNAPI_DISABLE_CPP_EXCEPTIONS' \
	'-DBUILDING_NODE_EXTENSION'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-exceptions \
	-fno-strict-aliasing \
	-std=gnu++17

INCS_Release := \
	-I/root/.cache/node-gyp/22.19.0/include/node \
	-I/root/.cache/node-gyp/22.19.0/src \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/config \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/22.19.0/deps/uv/include \
	-I/root/.cache/node-gyp/22.19.0/deps/zlib \
	-I/root/.cache/node-gyp/22.19.0/deps/v8/include \
	-I$(srcdir)/../node-addon-api \
	-I$(srcdir)/src \
	-I$(srcdir)/swisseph

OBJS := \
	$(obj).target/$(TARGET)/src/sweph.o \
	$(obj).target/$(TARGET)/src/functions.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(builddir)/swisseph.a $(obj).target/swisseph.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64

LIBS :=

$(obj).target/sweph.node: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/sweph.node: LIBS := $(LIBS)
$(obj).target/sweph.node: TOOLSET := $(TOOLSET)
$(obj).target/sweph.node: $(OBJS) $(obj).target/swisseph.a FORCE_DO_CMD
	$(call do_cmd,solink_module)

all_deps += $(obj).target/sweph.node
# Add target alias
.PHONY: sweph
sweph: $(builddir)/sweph.node

# Copy this to the executable output path.
$(builddir)/sweph.node: TOOLSET := $(TOOLSET)
$(builddir)/sweph.node: $(obj).target/sweph.node FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/sweph.node
# Short alias for building this executable.
.PHONY: sweph.node
sweph.node: $(obj).target/sweph.node $(builddir)/sweph.node

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/sweph.node

