# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := swisseph
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=swisseph' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_LARGEFILE_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS' \
	'-DDEBUG' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-exceptions \
	-fno-strict-aliasing \
	-std=gnu++17

INCS_Debug := \
	-I/root/.cache/node-gyp/22.19.0/include/node \
	-I/root/.cache/node-gyp/22.19.0/src \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/config \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/22.19.0/deps/uv/include \
	-I/root/.cache/node-gyp/22.19.0/deps/zlib \
	-I/root/.cache/node-gyp/22.19.0/deps/v8/include

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=swisseph' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_GLIBCXX_USE_CXX11_ABI=1' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_LARGEFILE_SOURCE' \
	'-D__STDC_FORMAT_MACROS' \
	'-DOPENSSL_NO_PINSHARED' \
	'-DOPENSSL_THREADS'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-exceptions \
	-fno-strict-aliasing \
	-std=gnu++17

INCS_Release := \
	-I/root/.cache/node-gyp/22.19.0/include/node \
	-I/root/.cache/node-gyp/22.19.0/src \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/config \
	-I/root/.cache/node-gyp/22.19.0/deps/openssl/openssl/include \
	-I/root/.cache/node-gyp/22.19.0/deps/uv/include \
	-I/root/.cache/node-gyp/22.19.0/deps/zlib \
	-I/root/.cache/node-gyp/22.19.0/deps/v8/include

OBJS := \
	$(obj).target/$(TARGET)/swisseph/swecl.o \
	$(obj).target/$(TARGET)/swisseph/swedate.o \
	$(obj).target/$(TARGET)/swisseph/swehel.o \
	$(obj).target/$(TARGET)/swisseph/swehouse.o \
	$(obj).target/$(TARGET)/swisseph/swejpl.o \
	$(obj).target/$(TARGET)/swisseph/swemmoon.o \
	$(obj).target/$(TARGET)/swisseph/swemplan.o \
	$(obj).target/$(TARGET)/swisseph/sweph.o \
	$(obj).target/$(TARGET)/swisseph/swephlib.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64

LIBS :=

$(obj).target/swisseph.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/swisseph.a: LIBS := $(LIBS)
$(obj).target/swisseph.a: TOOLSET := $(TOOLSET)
$(obj).target/swisseph.a: $(OBJS)
	$(call create_archive,$@,$^)

# Add target alias
.PHONY: swisseph
swisseph: $(obj).target/swisseph.a

# Add target alias to "all" target.
.PHONY: all
all: swisseph

# Add target alias
.PHONY: swisseph
swisseph: $(builddir)/swisseph.a

# Copy this to the static library output path.
$(builddir)/swisseph.a: TOOLSET := $(TOOLSET)
$(builddir)/swisseph.a: $(obj).target/swisseph.a FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/swisseph.a
# Short alias for building this static library.
.PHONY: swisseph.a
swisseph.a: $(obj).target/swisseph.a $(builddir)/swisseph.a

# Add static library to "all" target.
.PHONY: all
all: $(builddir)/swisseph.a

